apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-1
  labels:
    app: test-1
    kubernetes.azure.com/generator: devhub
  namespace: ns-test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-1
  template:
    metadata:
      labels:
        app: test-1
    spec:
      containers:
        - name: test-1
          image: aksauto20241129registry.azurecr.io/test-1-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
