apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-air-1
  labels:
    app: deploy-air-1
    kubernetes.azure.com/generator: devhub
  namespace: ns-contoso-air-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-air-1
  template:
    metadata:
      labels:
        app: deploy-air-1
    spec:
      containers:
        - name: deploy-air-1
          image: aksauto20241129registry.azurecr.io/contoso-air-1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
