apiVersion: v1
kind: Service
metadata:
  name: deploy-air-1
  namespace: ns-contoso-air-1
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: deploy-air-1
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000